### PR TITLE
Don't invoke the installer directly - use scripts

### PR DESCRIPTION
**Pull request by tejohnso**
@fjvallarino @ahmedalsudani  please review.

### CODE REVIEW

**Comment by fjvallarino** [comment]
:+1:

**Comment by ahmedalsudani** [comment]
@tejohnso does player need an update so it knows what the new `appPath` is?

**Comment by tejohnso** [comment]
Actually I think the appPath should be fine since the player jar is going to be in the version directory.  And that's also where the scripts are.  So the installer doesn't need to move them.

**Comment by ahmedalsudani** [comment]
@tejohnso that's where scripts used to be. Going forward, they're going to be either in `scripts/` or `installer/scripts/`

**Comment by tejohnso** [comment]
@ahmedalsudani Ok.  We just need to make the same directory change here in front of start.sh and start.bat

**Comment by ahmedalsudani** [comment]
@tejohnso yeah, I've already changed it. I realized the shortcuts reference `Installer/scripts` so I changed it. Just testing things locally now before pushing

**Comment by tejohnso** [comment]
@ahmedalsudani updated.

**Comment by ahmedalsudani** [comment]
:+1:

**Pull request merged**
