### PR TITLE
Load browser arguments configuration from .ini file

### PR DESCRIPTION
**Pull request by fjvallarino**
@tejohnso please review

### CODE REVIEW

**Comment by tejohnso** [comment]
Can we remove the start player chromeapp windows and run extended mode exe?  

I'm not sure "ignorebrowserpaths" makes sense as a config param.  If I saw that in a config file I don't think I'd guess that it has anything to do with the user-data-dir flag.

**Comment by fjvallarino** [comment]
@tejohnso Yes, it's not clear, but it also affects the cache dir, so it has to be somewhat generic. Do you have any suggestion?

I'll remove the methods (I'm pretty sure they are no longer used).

**Comment by tejohnso** [comment]
Couldn't they be added to the config file on first run?  
So we could have a user-data-dir flag in the config file with whatever its computed value is.  Same for the other flag

**Comment by fjvallarino** [comment]
@tejohnso Sounds good

**Comment by fjvallarino** [comment]
@tejohnso Updated

**Comment by tejohnso** [comment]
:+1:

**Pull request merged**
