### PR TITLE
Update player version

### PR DESCRIPTION
**Pull request by tejohnso**
@ahmedalsudani @fjvallarino I've updated the bucket components dir with this version of the player.

### CODE REVIEW

**Comment by fjvallarino** [comment]
:+1: 

@tejohnso we'll have to rebuild RisePlayer.tar.gz with updated .ver for the bundle

**Comment by ahmedalsudani** [comment]
:+1: though I have no idea what this is used for :sweat_smile:

**Comment by tejohnso** [comment]
@fjvallarino That's what I mean...I've already updated the tar.gz in the components dir

**Comment by tejohnso** [comment]
@ahmedalsudani It's used in BQ logging for player_version

**Pull request merged**
