### PR TITLE
Add tracking for successful restarts.

### PR DESCRIPTION
**Pull request by ahmedalsudani**
Assumptions:

- this program eventually becomes rvplayer

### CODE REVIEW

**Comment by ahmedalsudani** [comment]
@fjvallarino @tejohnso let me know if anything needs to change.

I went ahead and let my IDE format the code with 4 spaces. Are 4 spaces ok?

**Comment by tejohnso** [comment]
@ahmedalsudani Looks good :+1: 

Did you run any tests?  

Do we need a separate "successful restart" event?  I think we could add the status in the event details of the "startup" event that's already being logged.  So we'd have "startup", "from restart" if it was from a restart.

**Comment by ahmedalsudani** [comment]
@tejohnso ah, that makes more sense. On it.

I ran the few tests we have, and they reported success.

**Comment by ahmedalsudani** [comment]
@tejohnso derp. I should have understood what you meant. Done

**Comment by tejohnso** [comment]
:+1:

**Pull request merged**
