### PR TITLE
Integrate electron browser

### PR DESCRIPTION
**Pull request by fjvallarino**
@tejohnso @ahmedalsudani please review

### CODE REVIEW

**Comment by fjvallarino** [comment]
@tejohnso @ahmedalsudani updated

**Comment by tejohnso** [comment]
@ahmedalsudani @fjvallarino We're ok to merge this now?

**Comment by fjvallarino** [comment]
@tejohnso @ahmedalsudani pending your approval, actually

**Comment by ahmedalsudani** [comment]
:+1:

**Pull request merged**
