### PR TITLE
Fix history gesture issue

### PR DESCRIPTION
**Pull request by ahmedalsudani**
- pass a parameter to Chrome that disables scrolling through history
- this should fix Rise-Vision/viewer#80

### CODE REVIEW

**Comment by ahmedalsudani** [comment]
@fjvallarino @tejohnso ready for review.

Player tested on `Ubuntu 14.04 64-bit`, `Win 10 Home 64-bit`

The issue in question seems fixed on `Win 10 Home 64-bit`

**Comment by tejohnso** [comment]
So to confirm, we're not saving display properties anymore.  @fjvallarino sounds ok to you?

**Comment by fjvallarino** [comment]
@tejohnso Sounds good. The saving process was added here: https://github.com/Rise-Vision/rise-player/commit/72bca833f395ba10aa08cbe5c960bbe2d1eb2b1a#diff-090f34a06570611ae664470f97c72050

**Comment by ahmedalsudani** [comment]
@fjvallarino @tejohnso it looked like we were only saving the properties for the browser arguments, so I figured we'd do away with it.

**Pull request closed without merging**
